### ISSUE TITLE
BUG API Service v2

### ISSUE THREAD

**Issue by syatriia** [iqbalaey/MATA-Analytics#2]
Here some new bugs in API Service
[UNIT TESTING API v2.xlsx](https://github.com/iqbalaey/MATA-Analytics/files/1298752/UNIT.TESTING.API.v2.xlsx)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bugs backend](https://trello.com/c/c4mgQhal/61-fixing-bugs-backend)

**Comment by iqbalaey** [comment]
kindly add test description / story / steps how bug occur
should be fixed for now

**Comment by syatriia** [comment]
Still invalid return value group description
[Bug FE - API  13-09-2017.docx](https://github.com/iqbalaey/MATA-Analytics/files/1405582/Bug.FE.-.API.13-09-2017.docx)

**Comment by syatriia** [comment]
checked
