### ISSUE TITLE
Bug Solr Config

### ISSUE THREAD

**Issue by syatriia** [iqbalaey/MATA-Analytics#3]
Bug when delete dictionary in solr config
[Bug BE - overall checking 10-13-2017.docx](https://github.com/iqbalaey/MATA-Analytics/files/1389746/Bug.BE.-.overall.checking.10-13-2017.docx)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bugs backend](https://trello.com/c/c4mgQhal/61-fixing-bugs-backend)

**Comment by iqbalaey** [comment]
fix yak closed

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise bug solr](https://trello.com/c/MmYAJS8E/67-raise-bug-solr)

**Comment by syatriia** [comment]
Masih ngebug, 
pas ngebuat dictionary di satu topics, dictionary dari topics yang lain ikut kebuat
[Bug BE - 2017-10-20.docx](https://github.com/iqbalaey/MATA-Analytics/files/1401192/Bug.BE.-.2017-10-20.docx)
