### ISSUE TITLE
Bug API Plan Code

### ISSUE THREAD

**Issue by syatriia** [iqbalaey/MATA-Analytics#7]
return json plan code null, di database plan code user Free

Url: http://52.74.0.206:8080/maxapi/service/api/auth/login
Method: POST
Body: { "syatria" = "11syatriia" }

Expected Result : "plancode" : "Free"
Actual Result : "plancode" : null

![bug be - return user auth plan code](https://user-images.githubusercontent.com/13661944/32260035-ac6c4ad4-bef7-11e7-91cd-f92c42ed5df7.jpg)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug backend #2](https://trello.com/c/P6SmdZgO/105-fix-bug-backend-2)
